source :rubygems

gem 'rails', '3.1.0.rc5'
gem 'sqlite3'
gem 'jquery-rails'
gem 'haml'
gem 'sass'
gem 'coffee-script'
gem 'uglifier'
gem 'unicorn'
gem 'capistrano'
gem 'ruby-debug19', :require => 'ruby-debug'

group :test do
  gem 'turn', :require => false
end